# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34cc83f94887b9dad71255d00655c4bb8dc5a0587d2d494b0a68085ff72784ca5efce242daab2ec30cc45331a5602995ce6bc84c7217f1814c1132585d6608a2

test:
  secret_key_base: 1592a1d1bdd8da8a3bc0ce7c88e5473554d9320e6f221960720098f3c1bb4e53894d8e215bb83a4cc9b5097282637db7f01d26997d19819e4df27e761d8f2444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
